### ISSUE TITLE
Fix wrong type failures with set operations

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#418]
See [this build](https://github.com/zio/zio-redis/runs/3150937920) for more details.

**Comment by anovakovic01** [comment]
It looks like the output for the ZRANDMEMBER command is not properly passed. I'm not sure why this wasn't visible on the CI when the actual bug was introduced.

**Comment by anovakovic01** [comment]
This is what happened:
- some of the command output types (ZRANDMEMBER and SINTER) were in sync with the Redis 6.2 implementation at the time,
- when the Redis version 6.2.5 was released, our CI pulled it and tests started failing because the command behaviour changed.

Here is an example of such change from the Redis 6.2.5 release notes:
> * Fix reply type for HRANDFIELD and ZRANDMEMBER when key is missing (#9178).
  Was using a null array instead of an empty array.

I've sent the PR with the fix, but it won't work with the Redis versions between `6.2.0` and `6.2.4`.

@mijicd should we merge this PR or update our code in such a way that it works with both versions? Also, should we add such validation to the CI?
