### ISSUE TITLE
Add missing keys commands

### ISSUE THREAD

**Issue by mijicd** [zio/zio-redis#9]
Keys API currently doesn't support the following:

- `MIGRATE`
- `OBJECT`
- `RANDOMKEY`
- `RESTORE`
- `SORT`
- `WAIT`

Determine which of these are necessary, and represent them.

**Comment by mikail-khan** [comment]
I'll take this one.

**Comment by mikail-khan** [comment]
The followings keys are problematic:

1. `OBJECT` : Depending on the type of Redis sub-command the output type is different. The current design of the service does not support this.
2. `RANDOMKEY` : This does not take any input parameters. There is no way of specifying no input parameters with the current design.
3. `SORT`: The output type of this Redis command depends on what option the user has chosen. If the `store` option is passed an `Integer` returned and if the `store` option is not supplied, an `Array` is returned. The service design currently does not support this type of dependency between the options chosen and the output type.

`MIGRATE`,  `RESTORE`, and `WAIT` are good to go. I will raise a PR for them today.

There's one slight issue with `WAIT`. We cannot specify the `val` with a `wait` identifier inside the `Keys` trait. This is because it clashes with the `wait` method inside Java's `Object` type :upside_down_face:

**Comment by mijicd** [comment]
@mikail-khan regarding `randomkey`, there is a `NoInput`. Check out `Transactions` API. Let me think about the other ones over the PR review :).

**Comment by mijicd** [comment]
Closed in #51. Let's leave `object` out of scope for now.
